### ISSUE TITLE
Getting "TypeScript dictionary key type must be either 'number' or 'string'" for a property type "Dictionary<string,object>"

### ISSUE THREAD

**Issue by pellesantiago** [jburzynski/TypeGen#87] opened 2019-11-25 21:52 UTC
Hi,
Im getting this error:
Error when determining TypeScript type for C# type 'System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]': TypeScript dictionary key type must be either 'number' or 'string'

The key of the dictionary is a string.
Im using Nuget 2.4.7.

I had check your source code and appears to be fine. ¿What i am missing?
¿Its nuget 2.4.7 outdated?

Thanks

**Comment by jburzynski** [comment] 2019-12-04 16:21
Hi,
sorry for my late reply.

It looks like it may be a bug, but possibly not a simple one to fix - I have some acceptance tests that I run and they probably would detect things like this, that's why it looks like it may be not a trivial bug to fix.

Version 2.4.7 is the latest version.

It may help a bit if you could try to install some earlier versions to see if the bug appeared in some recent version.

Lately I haven't had too much time to work on TypeGen, but I'll look into this as soon as I have a chance.

**Comment by hihack** [comment] 2019-12-04 16:36
Don't worry. I had end up using https://frhagn.github.io/Typewriter/

Thanks anyway.
Typegen is really great but unfortunaly not for this case.

Regards,
Santiago

**Comment by jburzynski** [comment] 2019-12-15 16:14
Ok, I'm glad you found a tool that is good for what you need.

I'll keep this open anyway, because it's a bug and needs to be fixed.

**Comment by jburzynski** [comment] 2023-07-26 14:32
Closing - cannot reproduce.

**Closed by jburzynski** 2023-07-26 14:32 UTC

**Comment by rezaneam** [comment] 2024-07-30 10:28
@jburzynski I am observing the same issue when try to convert the following interface
`public interface IDailyReport 
{
    Dictionary<DateTime, double> Usage { get; }
}`

so I get this error `TypeScript dictionary key type must be either 'number', 'string' or an enum.` and that's because the regular dictionary in ts/js doesn't support date as key.
It could Map instead but I couldn't find any way to make it as `CustomTypeMappings`

**Comment by jburzynski** [comment] 2024-11-22 12:34
@rezaneam I can think of these 2 ways to generate a dictionary with a DateTime key:
- create a custom type mapping from `System.DateTime` to `string`, `number` or an enum type (but this affects all uses of `DateTime`)
- use [`TsTypeAttribute`](https://typegen.readthedocs.io/en/latest/attributes.html#tstypeattribute) (or `.Type()` in generation spec) to manually provide the dictionary type
